export const UPDATE_BOOLLOADING = "UPDATE_BOOLLOADING";

export const UPDATE_NOWSHOW = "UPDATE_NOWSHOW";
export const UPDATE_COMINGSHOW = "UPDATE_COMINGSHOW";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const UPDATE_CITY = "UPDATE_CITY";

export const UPDATE_DETAIL = "UPDATE_DETAIL";

export const UPDATE_CINEMA = "UPDATE_CINEMA";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_REG = "UPDATE_REG";
export const UPDATE_UDDATE_GETPASSWORD = "UPDATE_GETPASSWORD";

